android/android-test

- docs/espresso-setup.md
Without this the test doesn't compile, build fails with "java.lang.Exception: No runnable methods"
> Add @Test annotation to JUnit4 example test

- docs/espresso-snippets.md
This fixes the links markup to java code
> Fix extra parenthesis in code links

- docs/espresso-intents.md
- Added a newline before the last unordered list on the page so that the HTML renders as expected. (It renders correctly in GitHub, but not GitHub Pages.)
- Also added a small improvement for grammar.
> Small fix for Espresso Intents page

- docs/espresso-snippets.md
Removed a duplicated gravis.
Now the whichItemContent is highlighted \o/
> removed duplicated gravis

- _config.yml
- docs/accessibility.md
- docs/androidjunitrunner-guide.md
- docs/espresso-basic.md
- docs/espresso-cheatsheet.md
- docs/espresso-idling-resource.md
- docs/espresso-intents.md
- docs/espresso-lists.md
- docs/espresso-setup.md
- docs/espresso-snippets.md
- docs/espresso-web.md
- docs/espresso.md
- docs/index.md
- docs/junit4rules.md
- docs/uiautomator.md
- downloads.md
- index.md
- release_notes.md
- samples.md
Note that HELP and CONTRIBUTING are not redirected. 
Espresso Setup instructions is 404ing on DAC. Do not merge until that's fixed!
> Deprecation: Adds redirects to DAC

- Dockerfile
- WORKSPACE
- build_extensions/axt_versions.bzl
- cloudbuild.yaml
- core/java/androidx/test/core/content/pm/ApplicationInfoBuilder.java
- core/java/androidx/test/core/content/pm/PackageInfoBuilder.java
- core/java/androidx/test/core/view/MotionEventBuilder.java
- core/java/androidx/test/core/view/PointerCoordsBuilder.java
- core/java/androidx/test/core/view/PointerPropertiesBuilder.java
- core/javatests/androidx/test/core/content/pm/ApplicationInfoBuilderTest.java
- core/javatests/androidx/test/core/content/pm/PackageInfoBuilderTest.java
- core/javatests/androidx/test/core/view/MotionEventBuilderTest.java
- espresso/core/java/androidx/test/espresso/assertion/BUILD.bazel
- espresso/core/java/androidx/test/espresso/base/BUILD.bazel
- espresso/core/java/androidx/test/espresso/matcher/BUILD.bazel
- espresso/intents/java/androidx/test/espresso/intent/BUILD.bazel
- runner/android_junit_runner/java/androidx/test/BUILD.bazel
- runner/android_junit_runner/java/androidx/test/internal/runner/tracker/UsageTrackerRegistry.java
- runner/rules/java/androidx/test/BUILD.bazel
- services/AndroidManifest.xml
- services/speakeasy/java/androidx/test/services/speakeasy/server/BUILD.bazel
> Import from piper

- README.md
State to use combination of GitHub issue tracker, mailing list, and stack overflow.
> Update README.md Issues section

- README.md
- espresso/intents/java/androidx/test/espresso/intent/matcher/BUILD.bazel
> Fix bazel build by adding missing core dependency

- .gitignore
- README.md
- bazelci/buildkite-pipeline.yml
> Add build kite config

- repo.bzl
> Revert deleted bind for six

- ext/junit/java/androidx/test/ext/junit/rules/ActivityScenarioRule.java
> Update classdoc of ActivityScenarioRule

- WORKSPACE
- ext/junit/javatests/androidx/test/ext/junit/BUILD.bazel
- ext/truth/javatests/androidx/test/ext/truth/BUILD.bazel
- repo.bzl
> Update to robolectric 4.4.

- Dockerfile
- WORKSPACE
- runner/android_junit_runner/java/androidx/test/BUILD.bazel
- runner/android_junit_runner/javatests/androidx/test/BUILD.bazel
- runner/rules/java/androidx/test/BUILD.bazel
- runner/rules/javatests/androidx/test/rule/BUILD.bazel
- services/storage/javatests/androidx/test/services/storage/BUILD.bazel
- services/storage/javatests/androidx/test/services/storage/provider/BUILD.bazel
> Compile against android 30, use build tools 30.0.2.

- ext/truth/java/androidx/test/ext/truth/util/SparseBooleanArraySubject.java
- ext/truth/javatests/androidx/test/ext/truth/util/SparseBooleanArraySubjectTest.java
Adds SparseBooleanArraySubject for asserting about `SparseBooleanArray`s.
Closes #879.
> Add SparseBooleanArraySubject

- .github/workflows/build-test.yml
- WORKSPACE
- core/javatests/androidx/test/core/app/testing/BUILD.bazel
And remove bazel rules_proto mirror that returns 404.
> Add robolectric test run to GitHub Actions

- WORKSPACE
- repo.bzl
See https://github.com/robolectric/robolectric-bazel/releases/tag/4.7.3.
/cc @hoisie @brettchabot .
> Bump Robolectric to 4.7.3

- .gitignore
I think it's safe to ignore .idea entirely.
> Ignore .idea for Intellij IDEA

- CONTRIBUTING.md
> Update CONTRIBUTING.md description of CI environment

- runner/android_junit_runner/java/androidx/test/filters/LargeTest.java
- runner/android_junit_runner/java/androidx/test/filters/MediumTest.java
- runner/android_junit_runner/java/androidx/test/filters/SmallTest.java
> Test description edits

- CONTRIBUTING.md
> Update contributing guide to use bazelisk

- .github/workflows/build-test.yml
> Enhance GitHub Actions

- .github/actions/build-maven/action.yml
- .github/actions/gradle-emulator-tests/action.yml
> Fix gradle-emulator-tests github action.

- runner/android_junit_runner/java/androidx/test/filters/SmallTest.java
> Fixed typo.

- .github/actions/gradle-emulator-tests/action.yml
> Fix gradle test upload path.

- WORKSPACE
- build_extensions/axt_versions.bzl
> Update to kotlin 1.8.20.

- .github/workflows/ci.yml
Experimental change to guage the reliability and performance of using linux large runners for the build and test github actions
> Experiment with using large runners.

- .bazelproject
- CONTRIBUTING.md
> Refresh bazel IDE setup docs.

- gradle-tests/build.gradle
- gradle-tests/espresso/accessibility/build.gradle
- gradle-tests/espresso/build.gradle
- gradle-tests/espresso/contrib/build.gradle
- gradle-tests/espresso/idling_resource/build.gradle
- gradle-tests/espresso/web/build.gradle
- gradle-tests/gradle/wrapper/gradle-wrapper.properties
- gradle-tests/orchestrator/build.gradle
- gradle-tests/runner/build.gradle
Upgrade AGP, gradle version and explictly set the JVM target to 17.
> Allow gradletests to run locally on macbook.

- .github/workflows/ci.yml
- gradle-tests/build.gradle
- gradle-tests/gradle/wrapper/gradle-wrapper.properties
This should improve the GMD setup task flakiness.
> Upgrade AGP to 8.3.0-alpha17

- BUILD
- build_extensions/axt_versions.bzl
- gradle-tests/settings.gradle
androidx.test:orchestrator:1.5.0-alpha03
> Update artifacts and version numbers for 2024_02_29 release

- build_extensions/axt_versions.bzl
- gradle-tests/settings.gradle
> Increment minor versions after stable release branch cut

- espresso/device/CHANGELOG.md
- espresso/device/java/androidx/test/espresso/device/action/ScreenOrientationAction.kt
- espresso/device/java/androidx/test/espresso/device/common/ActivityUtil.kt
> Cherry-pick: Unregister callbacks outside of callback methods

- gradle-tests/orchestrator/build.gradle
- gradle-tests/orchestrator/src/androidTest/java/androidx/test/gradletests/orchestrator/OrchestratorTest.kt
> Add test with whitespace in orchestrator gradle tests.

- kokoro/test_artifacts.sh
> Cherrypick: Exclude espresso device tests from kokoro
