ext/truth/java/androidx/test/ext/truth/os/ParcelableSubject.java

It make possible to test `Parcelable` without writing a custom `Subject` class. 
resolve #238.

Change the access modifier of ParcelableSubject to public.

---

BUILD.bazel
WORKSPACE

This PR migrates the repo to use the new Maven transitive resolver and fetch in https://github.com/bazelbuild/rules_jvm_external.
This is a mechanical change that replaces `gmaven_rules` with `rules_jvm_external`, and `gmaven_artifact` with `artifact`. 
We also add an additional `maven_install` declaration to the WORKSPACE file to declare the top level targets we want to use.

Migrate legacy gmaven_rules to rules_jvm_external

---

WORKSPACE

This fixes the build to be compatible with `--incompatible_disallow_data_transition`.

Bump version of rules_kotlin

---

WORKSPACE

This version of the Kotlin rules include the fix for no-srcs on kt_android_library.

Update version of rules_kotlin

---

build_extensions/release.bzl
ext/junit/javatests/androidx/test/ext/junit/runners/BUILD.bazel
runner/monitor/javatests/androidx/test/internal/platform/BUILD.bazel

Use jarjar from new location, and specify manifests for unit tests to
avoid min sdk errors.

Fix build with bazel version 0.23.2 (hopefully)

---

README.md
WORKSPACE
repo.bzl

Make downstream Android instrumentation tests compatible with `--incompatible_new_actions_api` by updating Protobuf
https://github.com/bazelbuild/rules_jvm_external/issues/148
cc @laurentlb

Update protobuf version

---

tools/android/emulator/BUILD.bazel

See https://github.com/android/android-test/issues/373
See https://github.com/googlesamples/android-testing/issues/266
See https://github.com/bazelbuild/rules_jvm_external/issues/157

Set unified_launcher_head to PY2 to be compatible with --incompatible_use_python_toolchains

---

opensource/README.md
tools/device_broker/java/com/google/android/apps/common/testing/broker/AdbController.java
tools/device_broker/java/com/google/android/apps/common/testing/broker/Instrumentation.java
tools/device_broker/java/com/google/android/apps/common/testing/broker/InstrumentationRepository.java

Recognize cases like 'androidx.test/.runner.AndroidJUnitRunner', but
not 'com.somepackage/.AndroidJUnitRunner'

Fix AdbController's instrumentation class name enforcement.

---

espresso/intents/java/androidx/test/espresso/intent/Intents.java

Check for null `defaultInstance` member before invoking `internalRelease()`
When running tests in Android studio, I have routinely seen this error:
This pull request checks for a null reference before called in the `internalRelease()` method.

Check for null reference

---

runner/android_junit_runner/java/androidx/test/internal/runner/listener/InstrumentationResultPrinter.java

This change increases InstrumentationResultPrinter.MAX_TRACE_SIZE from 65,536 bytes to 131,072 bytes, giving more room for long stacktraces (think RxJava and also view hierarchy logged as part of the trace message).
Also attempts to fallback to getTrimmedTrace() before actively trimming the trace at a random point.

Increase InstrumentationResultPrinter.MAX_TRACE_SIZE

---

ktx/core/javatests/androidx/test/core/app/BUILD.bazel
ktx/ext/junit/javatests/androidx/test/ext/junit/rules/BUILD.bazel

Removes several build errors.
Closes #887.
Add testonly attribute to testonly targets.
With my extremely limited knowledge of bazel this looks like a bug with: 
```bazel
package(
default_testonly = 1,
)
```
Should probably be reported upstream in the bazel.

Add testonly attribute to testonly targets.

---

WORKSPACE
repo.bzl

Robolectric 4.7.2 is the latest stable release of Robolectric 4.7.x.
cc @hoisie @brettchabot .

Bump Robolectric to 4.7

---

WORKSPACE
repo.bzl

See https://github.com/robolectric/robolectric/releases/tag/robolectric-4.8.1 and https://github.com/robolectric/robolectric-bazel/releases/tag/4.8.1.  /cc @hoisie @brettchabot .

Bump Robolectric to 4.8.1

---

WORKSPACE

See https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.4.2.

Bump rules_jvm_external to 4.4.2

---

espresso/core/java/androidx/test/espresso/action/MotionEvents.java

fixes #1458 
Rather than trying to guess the toolType from the source/inputDevice,
if we have an event that we are copying from, we can just copy toolType
directly.
When we are NOT copying an event, we just fallback to the existing logic.

Fixes https://github.com/android/android-test/issues/1458

---

WORKSPACE
build_extensions/BUILD
build_extensions/mainDexClasses.rules
services/BUILD

This required copying the mainDexClasses rules from build tools 32, since build tools 33 no longer has that file.
Bug: 273280280

Switch to 33.0.2 build tools in bazel.

---

CONTRIBUTING.md
README.md

- Add more info on what projects are hosted on this repo
- Update release info now that github is used to tag releases again
- Remove mention of android instrumentation test execution for androidx.test libraries
- Update to mention build tools 33.0.2

Refresh README and CONTRIBUTING docs.

---

.gitignore
WORKSPACE

See https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.5.

Bump rules_jvm_external to 4.5

---

WORKSPACE
repo.bzl

See https://github.com/robolectric/robolectric-bazel/releases/tag/4.10.3.

Bump Robolectric to 4.10.3

---

.bazelrc

Attempt to workaround the periodic JVM crashes by configuring a sandbox_tmpfs_path

Override sandbox_tmpfs_path in 'test' GitHub Action job.

---

.github/workflows/ci.yml

Commit 5fcf70a6f3cff9d2593940a40be57bef00692595  removed the -Dorg.gradle.workers.max=1 flag in an attempt to speed up the job. Unfortunately it looks like the ob is ~30% flaky on github actions without this flag.

Restore the -Dorg.gradle.workers.max=1 flag in gradle-emulator-test.

---

.github/workflows/ci.yml

Setup the snapshot in a separate step so it can be cached. The hope is this will allow removal of the org.gradle.workers.max=1 limitation when performing the gradle build.

Setup gradle managed device in a separate step.

---

runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java
runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java

Fix ATO crashing when output filename exceeds 255 character limit

---

.github/workflows/ci.yml
WORKSPACE
build_extensions/robolectric.properties
repo.bzl

See https://github.com/robolectric/robolectric-bazel/releases/tag/4.11.1.
Although robolectric-bazel 4.11.1 recommends using rules_jvm_external 5.3, but this repository needs to keep using 4.5 until there is solution to fix the following error with latest rules_jvm_external:
```
ERROR: /home/runner/work/android-test/android-test/annotation/java/androidx/test/annotation/BUILD:38:15: in maven_artifact rule //annotation/java/androidx/test/annotation:annotation_maven_artifact: 
Traceback (most recent call last):
File "/home/runner/work/android-test/android-test/build_extensions/maven/maven_artifact.bzl", line 219, column 37, in _maven_artifact_impl
pom_content = _create_pom_string(ctx, group_id, artifact_id, version, packaging_type, maven_deps, ctx.attr.excluded_dependencies)
File …
```

Bump Robolectric to 4.11.1

---

build_extensions/maven/maven_artifact.sh

The maven artifact generation script used 'mktemp --suffix' which is apparently not available on mac. This commit just removes the '--suffix' argument since it is not strictly necessary.
Fixes #734

Fix building maven artifacts on mac.

---

.github/workflows/ci.yml

See https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/.

Bump GitHub's artifact action to v4

---

.github/workflows/ci.yml

~Update missed files by following https://github.com/android/android-test/pull/2057.~
Only add gradle wrapper validation job, and let other jobs depend on this new job to ensure full security. Thanks @TWiStErRob .

Update gradle files

---

.github/workflows/ci.yml

The default Linux runner are now 4 core/16 GB RAM with KVM: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

Switch back to default github runners.

---

.github/workflows/ci.yml

Previously the gradle-wrapper-validation task was a prerequisite for the build and test actions, which doesn't make sense since those actions do not use gradle.
Instead, make gradle-wrapper-validation a prerequisite only for the gradle-emulator-tests action. This should speed up CI latency by a few seconds, since now gradle-wrapper-validation can run in parallel.

CI: make gradle-wrapper-validation a prereq only in gradle tests.

---

core/CHANGELOG.md
core/java/androidx/test/core/api/current_public.txt
core/java/androidx/test/core/content/pm/ApplicationInfoBuilder.java
core/javatests/androidx/test/core/content/pm/ApplicationInfoBuilderTest.java

👋  Hi!
I'm currently trying to write a test for a class that consumes `ApplicationInfo.flags`.
Currently that is not writable by ApplicationInfoBuilder, therefore i was wondering if adding that capability would be acceptable. 
- Add a setter for ApplicationInfo.flags in the Builder-Class

Consider adding a setter to ApplicationInfoBuilder.flags

---

.github/workflows/ci.yml

Just execute gradle-wrapper-validation in gradle-emulator-tests to save overhead of running a separate job with checkout.
Also update to actions/checkout@v4

Inline gradle-wrapper-validation job.

---

runner/monitor/CHANGELOG.md
runner/monitor/java/androidx/test/platform/tracing/AndroidXTracer.java

Due to an android gradle bug calls to forceEnableAppTracing() may fail with NoSuchMethodError at runtime.
Instead of crashing, just catch and log this exception.

Catch and log exceptions when enabling tracing.

---

runner/monitor/java/androidx/test/BUILD
runner/monitor/java/androidx/test/internal/platform/app/ActivityInvokerDesugar.java
runner/monitor/java/androidx/test/jarjar.txt

Builds using ActivityScenario with older androidx.test.core:1.5.X but the latest androidx.test:monitor:1.7.X will see ActivityInvoker$-CC class not found errors. This is because androidx.test.core:1.5.X effectively depends on internal classes generated by the desugaring tool.
The latest androidx.test toolchain generates java8 bytecode and no longer generates these desugared classes.
To fix the backwards compatibility issues, this commit introduces a placeholder class ActivityInvokerDesugar that gets renamed to the missing ActivityInvoker$-CC class at build time.
Fixes #2259.

Fix ActivityInvoker$-CC class not found errors.

---

runner/monitor/java/androidx/test/BUILD
runner/monitor/java/androidx/test/internal/platform/app/ActivityInvokerDesugar.java
runner/monitor/java/androidx/test/jarjar.txt

Builds using ActivityScenario with older androidx.test.core:1.5.X but the latest androidx.test:monitor:1.7.X will see ActivityInvoker$-CC class not found errors. This is because androidx.test.core:1.5.X effectively depends on internal classes generated by the desugaring tool.
The latest androidx.test toolchain generates java8 bytecode and no longer generates these desugared classes.
To fix the backwards compatibility issues, this commit introduces a placeholder class ActivityInvokerDesugar that gets renamed to the missing ActivityInvoker$-CC class at build time.
Fixes #2259.

Cherry pick 'Fix ActivityInvoker$-CC class not found errors' to axt_2024_05_14_stable_release_branch

---

core/CHANGELOG.md
core/java/androidx/test/core/app/InstrumentationActivityInvoker.java

In "never be called after" the "be" is extraneous and should definitely be removed. I modified the entire phrase to what I think is more readable. If reviewers disagree, I can change this to only remove the "be" (or feel free to do it in a separate change).

Reword a precondition message

---

kokoro/build_artifacts.sh

These are now needed instead of 34.

Make kokoro install SDK 35 and build tools 35.0.0.

---

gradle-tests/build.gradle
gradle-tests/gradle/wrapper/gradle-wrapper.properties

The main motiviation is to ensure the tests are using a R8/D8 version that supports kotlin 2.1.0
https://developer.android.com/build/kotlin-support

Update gradle-tests to use latest stable AGP 8.9 and gradle 8.11.1.

---

MODULE.bazel

Cherrypick: Bazel: configure python to ignore root user error.

---

.github/workflows/ci.yml

This PR standardizes GitHub Actions triggers in workflow files within `.github/workflows/`.
The goal is to ensure workflows run consistently on `push`, `pull_request`, and `workflow_dispatch` events where appropriate.
This is part of a batch of pull requests across repositories owned by the `android` organization on GitHub.
**Project Owner:** Please review the changes carefully to ensure they are correct and appropriate for this project before approving and merging.
* If you do not think this change is appropriate (e.g., a workflow should NOT run on one of these triggers), please leave a comment explaining why.
* If you think the goal is appropriate but notice a mistake in the implementation, please leave a comment detailing the mistake.

Add triggers to .github/workflows/

---

espresso/CHANGELOG.md
espresso/core/java/androidx/test/espresso/base/ConfigurationSynchronizationUtils.java

This pull request fixes an issue I brought up a little while ago  (#2349) with multi-process + multi activity application that use different rotations between the activities.
Since the processes are different, an early return is added to allow for activities on other processes to have a rotation different from the main process.
Note: the fix only works on API 28 or later due to limitations from the public API.

Fix(espresso): Fix #2349

---

CONTRIBUTING.md

Update SDK install instructions in CONTRIBUTING.md

---

runner/android_test_orchestrator/CHANGELOG.md
runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java
runner/android_test_orchestrator/java/androidx/test/orchestrator/BUILD
runner/android_test_orchestrator/java/androidx/test/orchestrator/CallbackLogic.java
runner/android_test_orchestrator/java/androidx/test/orchestrator/TestRunnable.java
runner/android_test_orchestrator/stubapp/BUILD

Use of guava is unnecessary and currently results in ClassNotFoundExceptions on APIs <= 23.
Fixes #2422
PiperOrigin-RevId: 789467366

Cherry-pick: Remove guava from orchestrator.
